import { describe, it, expect, beforeAll } from 'vitest';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateRemoteFunctions } from '../generators/remote-functions.js';
import { generateRemoteErrorFile } from '../generators/remote-error.js';
import { resolveConfig } from '../config.js';
import type { OperationInfo, ParsedSpec } from '../types.js';

const parsed: ParsedSpec = {
  operations: [
    {
      operationId: 'Foods_GetFavorites',
      tag: 'V4 Foods',
      method: 'get',
      path: '/api/v4/foods/favorites',
      remoteType: 'query',
      invalidates: [],
      parameters: [],
      isVoidResponse: false,
      clientPropertyName: 'foodsV4',
    } satisfies OperationInfo,
  ],
  tags: ['V4 Foods'],
};

describe('shared error module emission', () => {
  it('emits remote-error.generated.ts alongside the tag files', () => {
    const files = generateRemoteFunctions(parsed, resolveConfig({}));
    expect(files.has('remote-error.generated.ts')).toBe(true);
  });

  it('delegates the catch block to the shared helpers', () => {
    const content = generateRemoteFunctions(parsed, resolveConfig({}))
      .get('foods.generated.remote.ts')!;

    expect(content).toContain("import { remoteErrorMessage, translateRemoteError } from './remote-error.generated.js';");
    expect(content).toContain("if (status === 403) { throw error(403, remoteErrorMessage(err, 'Forbidden')); }");
    expect(content).toContain("throw translateRemoteError(err, 'Failed to get favorites');");
    expect(content).not.toContain('JSON.parse');
  });

  it('omits the module and its import when no arm names it', () => {
    const files = generateRemoteFunctions(parsed, resolveConfig({
      errorHandling: {
        on401: "throw error(401, 'Unauthorized')",
        on403: "throw error(403, 'Forbidden')",
        on500: (fn) => `throw error(500, 'Failed to ${fn}')`,
      },
    }));

    expect(files.has('remote-error.generated.ts')).toBe(false);
    expect(files.get('foods.generated.remote.ts')!).not.toContain('remote-error.generated.js');
  });

  it('does not import a helper an arm only mentions in a comment', () => {
    const files = generateRemoteFunctions(parsed, resolveConfig({
      errorHandling: {
        on401: "throw error(401, 'Unauthorized')",
        on403: [
          '// translateRemoteError would redirect here; see remoteErrorMessage notes',
          "    throw error(403, 'Forbidden')",
        ].join('\n'),
        on500: (fn) => `throw error(500, 'Failed to ${fn}')`,
      },
    }));

    expect(files.has('remote-error.generated.ts')).toBe(false);
    expect(files.get('foods.generated.remote.ts')!).not.toContain('remote-error.generated.js');
  });

  it('imports only the helpers a custom arm names', () => {
    const content = generateRemoteFunctions(parsed, resolveConfig({
      errorHandling: {
        on403: "throw error(403, remoteErrorMessage(err, 'Nope'))",
        on500: (fn) => `throw error(500, 'Failed to ${fn}')`,
      },
    })).get('foods.generated.remote.ts')!;

    expect(content).toContain("import { remoteErrorMessage } from './remote-error.generated.js';");
    expect(content).not.toContain('translateRemoteError');
  });

  it('bakes the configured forward statuses into the module', () => {
    const content = generateRemoteErrorFile(resolveConfig({
      errorHandling: { forwardStatuses: [400, 422] },
    }));

    expect(content).toContain('new Set([400, 422])');
  });

  it('emits no header line restating the module name', () => {
    const content = generateRemoteErrorFile(resolveConfig({}));
    expect(content.split('\n').slice(0, 4)).toEqual([
      '// AUTO-GENERATED - DO NOT EDIT',
      '// Generated by openapi-remote-codegen',
      '',
      "import { error } from '@sveltejs/kit';",
    ]);
  });

  it('forwards 400, 409 and 429 by default', () => {
    const content = generateRemoteErrorFile(resolveConfig({}));
    expect(content).toContain('new Set([400, 409, 429])');
  });
});

describe('emitted error translation', () => {
  const outDir = resolve(dirname(fileURLToPath(import.meta.url)), '__generated__');
  let remoteErrorMessage: (err: unknown, fallback: string) => string;
  let translateRemoteError: (err: unknown, fallback: string) => never;

  /** An error shaped exactly as NSwag's ApiException throws it. */
  function apiException(status: number, response: string) {
    return {
      message: 'An unexpected server error occurred.',
      status,
      response,
      headers: {},
      result: null,
      isApiException: true,
    };
  }

  function thrownBy(run: () => never): { status: number; body: { message: string } } {
    try {
      run();
    } catch (err) {
      return err as { status: number; body: { message: string } };
    }
    throw new Error('expected a throw');
  }

  beforeAll(async () => {
    mkdirSync(outDir, { recursive: true });
    const config = resolveConfig({ imports: { kit: '../fixtures/kit-stub.js' } });
    writeFileSync(resolve(outDir, 'remote-error.generated.ts'), generateRemoteErrorFile(config), 'utf-8');
    const module = await import('./__generated__/remote-error.generated.js');
    remoteErrorMessage = module.remoteErrorMessage;
    translateRemoteError = module.translateRemoteError;
  });

  it('parses an ApiException whose response is a JSON string body', () => {
    const err = apiException(409, JSON.stringify({ error: 'Slug taken' }));
    expect(remoteErrorMessage(err, 'Failed to sign up')).toBe('Slug taken');
  });

  it('prefers ProblemDetails detail over title', () => {
    const err = apiException(400, JSON.stringify({ title: 'Bad Request', detail: 'Slug is reserved', status: 400 }));
    expect(remoteErrorMessage(err, 'Failed to sign up')).toBe('Slug is reserved');
  });

  it('flattens validation errors', () => {
    const err = apiException(400, JSON.stringify({ errors: { slug: ['required'] } }));
    expect(remoteErrorMessage(err, 'Failed to sign up')).toBe('required');
  });

  it('joins several validation errors', () => {
    const err = apiException(400, JSON.stringify({ errors: { slug: ['required', 'too short'], email: ['invalid'] } }));
    expect(remoteErrorMessage(err, 'Failed to sign up')).toBe('required, too short; invalid');
  });

  it('falls back when the body is not JSON', () => {
    const err = apiException(500, '<html>502 Bad Gateway</html>');
    expect(remoteErrorMessage(err, 'Failed to sign up')).toBe('Failed to sign up');
  });

  it('never surfaces the client library boilerplate message', () => {
    const err = apiException(500, '');
    expect(remoteErrorMessage(err, 'Failed to sign up')).toBe('Failed to sign up');
  });

  it('reads a deserialized object result directly', () => {
    const err = { ...apiException(403, ''), result: { detail: 'Not an administrator' } };
    expect(remoteErrorMessage(err, 'Forbidden')).toBe('Not an administrator');
  });

  it('reads a ProblemDetails thrown directly, without an exception wrapper', () => {
    const err = { status: 400, title: 'Bad Request', detail: 'Slug is reserved' };
    expect(remoteErrorMessage(err, 'Failed to sign up')).toBe('Slug is reserved');
  });

  it('forwards a configured status with the server reason', () => {
    const err = apiException(409, JSON.stringify({ error: 'Slug taken' }));
    expect(thrownBy(() => translateRemoteError(err, 'Failed to sign up'))).toEqual({
      status: 409,
      body: { message: 'Slug taken' },
    });
  });

  it('surfaces the reason a failed upload carried, not the thrown Error text', () => {
    // The shape the generated upload and url-encoded paths throw on a non-ok response.
    const err = Object.assign(new Error('Upload failed (400)'), {
      status: 400,
      response: JSON.stringify({ detail: 'Too large' }),
    });

    expect(remoteErrorMessage(err, 'Failed to upload')).toBe('Too large');
    expect(thrownBy(() => translateRemoteError(err, 'Failed to upload'))).toEqual({
      status: 400,
      body: { message: 'Too large' },
    });
  });

  it('collapses an unforwarded status to a 500 carrying the caller fallback', () => {
    // Nothing the API did not write for the user reaches the user: an unhandled
    // exception's detail is a stack trace under a development configuration.
    const err = apiException(500, JSON.stringify({ detail: 'System.NullReferenceException at Foo.Bar()' }));
    expect(thrownBy(() => translateRemoteError(err, 'Failed to sign up'))).toEqual({
      status: 500,
      body: { message: 'Failed to sign up' },
    });
  });

  it('reads past a typed result whose fields are empty to the body that has the reason', () => {
    // NSwag deserializes a declared error schema into `result`; when the response
    // does not match that schema the object is present but says nothing.
    const err = {
      ...apiException(409, JSON.stringify({ error: 'Slug taken' })),
      result: { traceId: '00-abc-01', extensions: {} },
    };
    expect(remoteErrorMessage(err, 'Failed to sign up')).toBe('Slug taken');
  });

  it('ignores an empty typed result in favour of a ProblemDetails response', () => {
    const err = {
      ...apiException(400, JSON.stringify({ title: 'Bad Request', detail: 'Slug is reserved' })),
      result: { errors: {}, title: '' },
    };
    expect(remoteErrorMessage(err, 'Failed to sign up')).toBe('Slug is reserved');
  });

  it('never surfaces the text of a transport or runtime failure', () => {
    const err = Object.assign(new Error('fetch failed'), {
      cause: new Error('connect ECONNREFUSED 127.0.0.1:5000'),
    });
    expect(remoteErrorMessage(err, 'Failed to sign up')).toBe('Failed to sign up');
  });

  it('ignores validation entries that carry no message', () => {
    const err = apiException(400, JSON.stringify({ errors: { slug: [null, null] } }));
    expect(remoteErrorMessage(err, 'Failed to sign up')).toBe('Failed to sign up');
  });

  it('keeps the entries that do have a message when a sibling is empty', () => {
    const err = apiException(400, JSON.stringify({ errors: { slug: [null, 'required'], email: [''] } }));
    expect(remoteErrorMessage(err, 'Failed to sign up')).toBe('required');
  });

  it('treats a whitespace-only reason as no reason', () => {
    const err = apiException(400, JSON.stringify({ detail: '   ' }));
    expect(remoteErrorMessage(err, 'Failed to sign up')).toBe('Failed to sign up');
  });
});
