import type { GeneratorConfig } from '../config.js';
import { resolveOn401 } from '../config.js';

/** File name of the shared error-translation module, inside the remote functions dir. */
export const REMOTE_ERROR_FILE = 'remote-error.generated.ts';

/** Import specifier the tag files use for {@link REMOTE_ERROR_FILE}. */
const REMOTE_ERROR_SPECIFIER = './remote-error.generated.js';

/** Everything {@link generateRemoteErrorFile} exports, in import order. */
const EXPORTS = ['remoteErrorMessage', 'translateRemoteError'] as const;

/**
 * The exports the configured catch arms actually name.
 *
 * The arms are opaque code, so the only way to know whether the shared module is
 * needed — by the defaults or by a consumer's own arm calling into it — is to
 * look for its names in the code about to be emitted.
 */
export function remoteErrorExportsUsedBy(config: GeneratorConfig): string[] {
  const { errorHandling } = config;
  const arms = [
    resolveOn401(errorHandling.on401, 'query'),
    resolveOn401(errorHandling.on401, 'command'),
    resolveOn401(errorHandling.on401, 'form'),
    errorHandling.on403,
    errorHandling.on500('operation'),
  ];
  return EXPORTS.filter(name => arms.some(arm => arm.includes(name)));
}

/** The import line for the shared module, or '' when no arm uses it. */
export function generateRemoteErrorImport(config: GeneratorConfig): string {
  const used = remoteErrorExportsUsedBy(config);
  if (used.length === 0) return '';
  return `import { ${used.join(', ')} } from '${REMOTE_ERROR_SPECIFIER}';\n`;
}

export function generateRemoteErrorFile(config: GeneratorConfig): string {
  const forwarded = config.errorHandling.forwardStatuses.join(', ');
  return `// AUTO-GENERATED - DO NOT EDIT
// Generated by openapi-remote-codegen
// Shared error translation for generated remote functions

import { error } from '${config.imports.kit}';

/** Statuses rethrown under their own status rather than collapsed into a 500. */
const FORWARDED_STATUSES = new Set([${forwarded}]);

type ErrorBody = Record<string, unknown>;

function asBody(value: unknown): ErrorBody | undefined {
  if (typeof value === 'string') {
    try {
      const parsed: unknown = JSON.parse(value);
      return typeof parsed === 'object' && parsed !== null ? (parsed as ErrorBody) : undefined;
    } catch {
      return undefined;
    }
  }
  return typeof value === 'object' && value !== null ? (value as ErrorBody) : undefined;
}

/**
 * The response body carried by a thrown API error, parsed.
 *
 * A generated HTTP client hands the body over unparsed — NSwag puts the raw text
 * on \`response\` and the deserialized body on \`result\`, and fills \`message\` with a
 * fixed string of its own — so an error that carries a body separately is never
 * itself a candidate body.
 */
function errorBody(err: unknown): ErrorBody | undefined {
  if (typeof err !== 'object' || err === null) return undefined;
  const e = err as Record<string, unknown>;
  const carriesResponse = 'result' in e || 'response' in e || 'body' in e;
  return asBody(e.result) ?? asBody(e.response) ?? asBody(e.body) ?? (carriesResponse ? undefined : asBody(e));
}

function flattenValidationErrors(errors: unknown): string | undefined {
  if (typeof errors !== 'object' || errors === null) return undefined;
  const messages = Object.values(errors as Record<string, unknown>)
    .map((value) => (Array.isArray(value) ? value.join(', ') : value))
    .filter((value): value is string => typeof value === 'string' && value.trim() !== '');
  return messages.length > 0 ? messages.join('; ') : undefined;
}

function text(value: unknown): string | undefined {
  return typeof value === 'string' && value.trim() !== '' ? value : undefined;
}

/** The server's own reason for \`err\`, or \`fallback\` when the response carried none. */
export function remoteErrorMessage(err: unknown, fallback: string): string {
  const body = errorBody(err);
  return (
    flattenValidationErrors(body?.errors) ??
    text(body?.error) ??
    text(body?.detail) ??
    text(body?.title) ??
    text(body?.message) ??
    fallback
  );
}

/** Rethrow \`err\` as a SvelteKit error carrying the server's reason. */
export function translateRemoteError(err: unknown, fallback: string): never {
  const status = (err as { status?: unknown } | null | undefined)?.status;
  const message = remoteErrorMessage(err, fallback);
  if (typeof status === 'number' && FORWARDED_STATUSES.has(status)) error(status, message);
  error(500, message);
}
`;
}
