import type { GeneratorConfig } from '../config.js';
import { resolveOn401 } from '../config.js';

export const REMOTE_ERROR_FILE = 'remote-error.generated.ts';

const REMOTE_ERROR_SPECIFIER = './remote-error.generated.js';

const EXPORTS = ['remoteErrorMessage', 'translateRemoteError'] as const;

/**
 * The exports the configured catch arms actually call.
 *
 * The arms are opaque code, so the only way to know whether the shared module is
 * needed — by the defaults or by a consumer's own arm calling into it — is to
 * look for calls to it in the code about to be emitted.
 */
export function remoteErrorExportsUsedBy(config: GeneratorConfig): string[] {
  const { errorHandling } = config;
  const arms = [
    resolveOn401(errorHandling.on401, 'query'),
    resolveOn401(errorHandling.on401, 'command'),
    resolveOn401(errorHandling.on401, 'form'),
    errorHandling.on403,
    errorHandling.on500('operation'),
  ];
  return EXPORTS.filter(name => {
    const call = new RegExp(String.raw`\b${name}\s*\(`);
    return arms.some(arm => call.test(arm));
  });
}

export function generateRemoteErrorImport(config: GeneratorConfig): string {
  const used = remoteErrorExportsUsedBy(config);
  if (used.length === 0) return '';
  return `import { ${used.join(', ')} } from '${REMOTE_ERROR_SPECIFIER}';\n`;
}

export function generateRemoteErrorFile(config: GeneratorConfig): string {
  const forwarded = config.errorHandling.forwardStatuses.join(', ');
  return `// AUTO-GENERATED - DO NOT EDIT
// Generated by openapi-remote-codegen

import { error } from '${config.imports.kit}';

/** Statuses rethrown under their own status rather than collapsed into a 500. */
const FORWARDED_STATUSES = new Set([${forwarded}]);

type ErrorBody = Record<string, unknown>;

function asBody(value: unknown): ErrorBody | undefined {
  if (typeof value === 'string') {
    try {
      const parsed: unknown = JSON.parse(value);
      return typeof parsed === 'object' && parsed !== null ? (parsed as ErrorBody) : undefined;
    } catch {
      return undefined;
    }
  }
  return typeof value === 'object' && value !== null ? (value as ErrorBody) : undefined;
}

/**
 * Every place a thrown API error might be carrying the response body.
 *
 * A generated HTTP client hands the body over in more than one shape at once —
 * NSwag puts the raw text on \`response\` and, for a declared error schema, a
 * deserialized object on \`result\` — and the object it deserialized may be the
 * one with nothing in it, so each has to be tried in turn rather than the first
 * object winning. An Error's own \`message\` is the client's or the runtime's text
 * ("fetch failed", a connection refusal), never the server's, so an Error is not
 * a candidate body for itself.
 */
function candidateBodies(err: unknown): ErrorBody[] {
  if (typeof err !== 'object' || err === null) return [];
  const e = err as Record<string, unknown>;
  const carriesResponse = 'result' in e || 'response' in e || 'body' in e;
  const candidates = [asBody(e.result), asBody(e.response), asBody(e.body)];
  if (!carriesResponse && !(err instanceof Error)) candidates.push(asBody(e));
  return candidates.filter((body): body is ErrorBody => body !== undefined);
}

function flattenValidationErrors(errors: unknown): string | undefined {
  if (typeof errors !== 'object' || errors === null) return undefined;
  const messages: string[] = [];
  for (const value of Object.values(errors as Record<string, unknown>)) {
    const items = (Array.isArray(value) ? value : [value]).filter(
      (item): item is string => typeof item === 'string' && item.trim() !== ''
    );
    if (items.length > 0) messages.push(items.join(', '));
  }
  return messages.length > 0 ? messages.join('; ') : undefined;
}

function text(value: unknown): string | undefined {
  return typeof value === 'string' && value.trim() !== '' ? value : undefined;
}

function bodyMessage(body: ErrorBody): string | undefined {
  return (
    flattenValidationErrors(body.errors) ??
    text(body.error) ??
    text(body.detail) ??
    text(body.title) ??
    text(body.message)
  );
}

/** The server's own reason for \`err\`, or \`fallback\` when no body carried one. */
export function remoteErrorMessage(err: unknown, fallback: string): string {
  for (const body of candidateBodies(err)) {
    const message = bodyMessage(body);
    if (message !== undefined) return message;
  }
  return fallback;
}

/**
 * Rethrow \`err\` as a SvelteKit error; terminates because \`error()\` throws.
 *
 * Only a forwarded status carries the server's text. Everything else collapses
 * to a 500 with the caller's fallback, because an unforwarded failure is one the
 * API did not write for the user — an unhandled exception's detail, in a
 * development configuration, is a stack trace.
 */
export function translateRemoteError(err: unknown, fallback: string): never {
  const status = (err as { status?: unknown } | null | undefined)?.status;
  if (typeof status === 'number' && FORWARDED_STATUSES.has(status)) {
    error(status, remoteErrorMessage(err, fallback));
  }
  error(500, fallback);
}
`;
}
